Add missing punctuation to error message
Before:

```
ERROR: This script does not work on Python 3.7 The minimum supported Python
version is 3.8. Please use https://bootstrap.pypa.io/pip/3.7/get-pip.py instead.
```

After:

```
ERROR: This script does not work on Python 3.7. The minimum supported Python
version is 3.8. Please use https://bootstrap.pypa.io/pip/3.7/get-pip.py instead.
```